### ISSUE TITLE
Is it possible to control the webojiCanvas (weboji) externally?

### ISSUE THREAD

**Issue by kinyat** [jeeliz/jeelizWeboji#10]
Hi,

We are trying to control the webojiCanvas (weboji) externally by separating the JEEFACETRANSFERAPI face-detection logic and the control of weboji.

Our idea is to send the face-detection data remotely through the net and control the weboji in the other side.

However, we found that the control of the weboji is deep down in the JEEFACETRANSFERAPI.

We want to ask if there is any way we can achieve what we want through this library, please?

If not, can you suggest what kind of tools, libraries or tutorials we should look for, please?

Thanks for your helps!

**Comment by xavierjs** [comment]
Hi,

This is doable currently.
The Three.js helper 
https://github.com/jeeliz/jeelizWeboji/blob/master/helpers/threejs/ThreeJeelizHelper.js
get the rotation value with:
```
rotation=JEEFACETRANSFERAPI.get_rotationStabilized();
```
and the morph coefficients with:
```
var morphTargetInfluencesDst=JEEFACETRANSFERAPI.get_morphTargetInfluencesStabilized();
```
These are the whole detection data.

Instead of drawing directly the THREE.JS animated mesh, you have to send these values through websockets and handle the rendering on the other side.
It is not easy to do, but doable :). 

Best,
Xavier

**Comment by kinyat** [comment]
@xavierjs Thanks :)

Just one more question, is it possible to have multiple JEEFACETRANSFERAPI running at the same time with different video sources?

Cheers

Eric

**Comment by xavierjs** [comment]
Hi,

It would be doable, but not advisable.
This lib is still quite computationnally intensive. If you process 2 different video sources, then you will have 2 times less computing power for each source. So it will process 2 times less detection per seconds for each source, and the result may be less responsive, or more noisy.

Best,
Xavier

**Comment by kinyat** [comment]
Thanks for answering :D
