### ISSUE TITLE
Is jeelizFaceTransfer open source ?

### ISSUE THREAD

**Issue by mianor64** [jeeliz/jeelizWeboji#15]
Hi,

First, congrats for this project. it's amazing !
I'd like to learn more about how jeelizFaceTransfer works but the file is minified. Is this an open source project ?
I am trying to make weboji works smooth on mobile devices. The SVG demo is smooth on a high-end laptop but lags on mobile devices (really slow on a 2 year-old Samsung A5). It seems that the face detection is the main cause of those lags. Maybe something like Dlib (landmarks detection) + FACS (facial action coding system) could improve expression detection?

Thanks

**Comment by xavierjs** [comment]
Hi,

Thank you for your support.
Unfortunately, it is not opensource.
Some of the reasons are explained here: https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2
The expression recognition is quite computationnaly intensive, and the Samsung A5 is really the minimum for Jeeliz libraries. I tested the different demos with this phone and the GPU is not very powerful. For Facefilter (https://github.com/jeeliz/jeelizFaceFilter) it works better because the task is easier. But for weboji it is a bit too low.

Best,
Xavier
