### ISSUE TITLE
Jeeliz Exposure controller in Jeeliz Weboji for improving lighting

### ISSUE THREAD

**Issue by Andyjoedev** [jeeliz/jeelizWeboji#16]
Hi, 

Sorry for bothering you again. 

I have checked your repo [https://github.com/jeeliz/jeelizExposureController](url) and I think it is really good. I have a suggestion, since Weboji needs good lighting conditions to perform better, have you tried adding exposure controller to weboji for improving expression results.

This may not work for face filter because it requires a webcam stream canvas/video behind the filter. But for weboji it will improve the results under bad lighting conditions (back-light, low or uneven light). However I believe the tracking effectiveness of the face will remain constant.

Have you tried to integrate them already?  If not then is there a reason for not doing so? 

I would love to try the same and share my experiences with you. Please guide.

Thanks and Regards,
Andy

**Comment by xavierjs** [comment]
Hi @Andyjoedev 

https://github.com/jeeliz/jeelizExposureController is good but still very experimental.
It relies on ImageCapture API which is not very widespread... It works only with Chrome (https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture ) . Even Firefox does not implement it, and I don't even think about Safari :( .

Also, one problem of using this library is, if the user is on a poorly enlighted room, this library will increase a lot the camera aperture value. Then, grain will appear on the image, or kinetic blur and it will lead to bad results detecting the expressions.

I think currently a camera feedback is still the best way for the user to see if there is a good lighting.
On the futur yeah it will be a nice idea. 

At the beginning the ExposureController was done to improve https://github.com/jeeliz/jeelizPupillometry but I never takes the time to add the feature. I can still add the possibility to provide a raw texture as input for jeelizWeboji and a predefined gl-context so that the merging would be possible. I will see when I will have time.

Best,
Xavier
