### ISSUE TITLE
Safari Version 13.0 (15608.1.24.40.4) Error

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizWeboji#18]
Hi @xavierjs!

I'm experimenting with the JEELIZFACETRANSFER today and receive this error when previewing in Safari:
[Log] ERROR in ContextFeedForward :  – "Your configuration cannot process color buffer float" (jeelizFaceTransfer.js, line 45)

[Log] ERROR in JeelizSVGHelper - CANNOT INITIALIZE JEEFACETRANSFERAPI : errCode = – "GL_INCOMPATIBLE" (JeelizSVGHelper.js, line 34)

I tested Safari on both https://webglreport.com/?v=2 and https://webglreport.com/?v=1.

Any ideas what the issue might be? Let me know if I can send you anything.

Thanks!

**Comment by xavierjs** [comment]
Hi Andrew,

Thank you for this detailed bug report.

On IOS12, even if WebGL2 is implemented we use WebGL1 because a part of the standard is not implemented correctly (we cannot do render to texture with a HALF_FLOAT precision).

I did the limitation only for IOS12, hoping that it would have been corrected with IOS13 but it seems to not have been corrected. I will upload and rebuild Jeeliz libraries.

Best,
Xavier

**Comment by xavierjs** [comment]
It should work since the last commit :)

**Comment by xavierjs** [comment]
Hi Andrew,

I tested with an Iphone XR and IOS 13.2

**Comment by xavierjs** [comment]
(I clicked on the wrong link, that's why I closed then re-open the issue)

**Comment by xavierjs** [comment]
Hi @andrewdeutsch 

Do you still have this bug?
It may be the same than https://github.com/jeeliz/jeelizFaceFilter/issues/85

Thanx,
Xavier

**Comment by xavierjs** [comment]
It should be fixed with the latest commit (https://github.com/jeeliz/jeelizWeboji/commit/c303558fe43a2eca303e7ead5c65e598aa4e1258)
This was due to an incomplete WebGL2 implementation on MacOSX 10.15 (Catalina).
Feel free to re-open it if the issue happens again.
