### ISSUE TITLE
Problem  : what's the scale and the position of the mesh should match the fox scale and position ? 

### ISSUE THREAD

**Issue by Rosko5** [jeeliz/jeelizWeboji#2]

**Comment by xavierjs** [comment]
What is that issue ? The code of the fox demo is clear enough, the position and the scale are well defined. First you should learn the basics of 3D algorithmic and THREE.js before doing 3D programming. You can learn it here: http://webglacademy.com 

I close the issue because It has nothing to do with the library. I am not here to give a beginner level 3D/THREE.JS or 3D infographic course.
