### ISSUE TITLE
Can I save this 3D animation video locally?

### ISSUE THREAD

**Issue by chenflood** [jeeliz/jeelizWeboji#20]
Hi, This looks cool and interesting. I can use any external video I'm interested in and convert it into 3D animation. I want to know if I can save the converted animation locally instead of just opening the browser to watch it.

**Comment by xavierjs** [comment]
Hi,

You cannot save the animation as a GIF easily.
This issue is related to the problem: https://github.com/jeeliz/jeelizFaceFilter/issues/27

With Chrome/Firefox some APIs like canvasrecorder can make the job.
But with Safari there is no way (Thx Apple).

In all cases, you still have to record separately sound and video and assemble on server side.
We can provide a solution (used in http://webojis.com/ ) but it is still experimental.

We can add the possibility to use external video source as a development service. You can contact contact__at__jeeliz.com for more information.

Best,
Xavier
