### ISSUE TITLE
M is not a function on jeefacetransferapi on init method

### ISSUE THREAD

**Issue by elcurioso95** [jeeliz/jeelizWeboji#21]
solved. There was some params missing !

**Comment by xavierjs** [comment]
Hi @elcurioso95 
Thank you for your bug report. 
As you have found, it was because `callbackReady` was not specified.
I have pushed a minor change, now you don't need to provide this function as parameter.
But it is still strongly advised to use it to handle errors and to launch the app only when the library is ready.

**Comment by xavierjs** [comment]
I close the issue, please re-open it if the bug is still here.
