### ISSUE TITLE
Can I use an image as a source?

### ISSUE THREAD

**Issue by avseoul** [jeeliz/jeelizWeboji#28]
Hi, first of all, thanks for this amazing library!

I'm trying to make an app that tracks the face in the image source. What I did is drawing the image to the `HTMLCanvasElement` and making it a `MediaStream` by using [.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) and updating the source of the `<video>` linked to your lib with it. 
It seems to barely work, it only works for very limited type of images but it mostly even fails to begin tracking. 

Is there a better way to track the face from the single image, which you would recommend? Please let me know. 

Thanks!

**Comment by xavierjs** [comment]
Hi @avseoul 

Unfortunately this library is really not suited for processing image.
The same neural network is used to detect and track the face, and to detect face morphs.
So it works as a state machine. And then there is a stabilization mechanism for face morphs factors.

So yes, currently there is no easy way to track face from a single image. Also I really thing that this task should be done on server side because there is no real-time constraint. it would also save computing power on client side for the rest of your app. If I were you I would go for a node.js service relying on an opencv based solution like STASM (I think there are better stuffs now).

Best,
Xavier

**Comment by avseoul** [comment]
Hi @xavierjs 

Thanks for your response in detail. I'll try the solutions that you suggested. Thanks again!

Best,
av
