### ISSUE TITLE
How to reduce CPU-GPU consumption

### ISSUE THREAD

**Issue by vinguyen** [jeeliz/jeelizWeboji#38]
Hello @xavierjs ,
Thanks for great lib, I'm using this lib for my personal project but it consume quite much CPU and GPU so question that are there any options to optimize this even reduce the frame rate or accuracy?

**Comment by xavierjs** [comment]
Hi @vinguyen 

You can add some delay between 2 detection frame using (JEEFACETRANSFERTAPI.set_animateDelay - see https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf )

But if this library uses computing power, it is because it needs it. On cheap devices it can be a problem, but it should work correctly on recent devices.
