### ISSUE TITLE
Seperate Texture files and new emotions

### ISSUE THREAD

**Issue by timsun28** [jeeliz/jeelizWeboji#39]
I would first like to thank you for this library! I have been trying to implement different kind of models, but I'm not sure how I would go along with adding multiple texture files to a model. 

In my case this would be for example a skin.png and some teeth.png and an eye.png. 

Would this be possible to add to the ThreeJeelizHelper.js? 

I was also wondering if it would be possible to add different face 'emotions'. For example stick out your tongue or move your eye balls to left/right/up/down? I'm not very experienced with training a model for this, but I was wondering if this could be added to the library or if you could suggest some way for me to add this functionality to my app / your library?

Thank you in advance!

**Comment by xavierjs** [comment]
Hi @timsun28,

Yes, it is possible to use more complex models, using several textures.
This library relies on Jeeliz Face Transfer to get face morph coefficient to then animate the 3D mesh.
Jeeliz Face Transfer is minified and the documentation is here: https://github.com/jeeliz/jeelizWeboji/blob/master/doc/jeefacetransferAPI.pdf

But the whole 3D part (animation, mesh instantiation, ...) is not minified.
What is a bit tricky is that we had to implement our own morphing system.
Because THREE.js Morph cannot take account of so many morphs (we need 11 morphs).

To implement new face emotions we have to train a new neural network model. It is very doable but we charge for this. If you have a specific request about training a neural network model you can ask me directly at xavier__at__jeeliz.com

Best,
Xavier
