### ISSUE TITLE
Possible to get two emoji on the screen?

### ISSUE THREAD

**Issue by GrandPoohBear** [jeeliz/jeelizWeboji#50]
I'm playing around with an idea, and trying to get two different raccoons on the screen (from the THREE.js demo) parroting expressions back to each other.  I've been looking through the code, but haven't found a good spot to instantiate the second mesh.  It always seems like there's some code referring to the first mesh in a global way.

Any suggestions?  Places you can recommend I look?

**Comment by xavierjs** [comment]
Hi,

it is not possible yet, but the experience would be bad since there would be twice less computing power per animoji.
Currently, the performance is adaptative: the more powerful the device is, the more we do detections per second, the more stabilized and responsive is the result.

The feature will be implemented in the next months I think but is really not my priority currently, it depends on my schedule.

Best,
Xavier
