### ISSUE TITLE
is there any way to set a fixed position while _isDetected == false?

### ISSUE THREAD

**Issue by arauko** [jeeliz/jeelizWeboji#52]
Hello,

Is there a way to set the values until the face is detected? (Ex: morph_X = -0.5486651)

I have been able to modify the values and freeze the rotation of waiting stance, but I am trying that during that position, it makes random faces like smiling, getting angry, etc. while the face is not detected but the values are "reset" in 1 ms after i changed...

how can i set this values and avoid the default values?

thanks in advance

**Comment by xavierjs** [comment]
The morph parameters are applied in ThreeJeelizHelper.js:
```
morphJeelizInfluences: _three.morphAnimMesh.userData.morphJeelizInfluences
```
This array of morph coefficient is directly updated by the lib.
When face is not detected you can replace this array by the array with your own static morph coefficients.
This array is applied by the material since the Shader is implemented in the material.
Then if the face is detected again you change back the array to the original array.
But allocate a new array, don't use the current array.
