### ISSUE TITLE
Weboji disappearing

### ISSUE THREAD

**Issue by bastien-teix** [jeeliz/jeelizWeboji#65]
### Problem
Hello !  
I'm using JeelizWeboji and sometimes the 3D model disappear after a while when we are not in front of the webcam... (Average 30min-1h)
Event if we are facing the webcam, the 3D model does not show up...
At the moment, we will refresh the page every 15min but it may be not really efficient...
For context, our app will be on a PC (with screen & webcam) will be up (turned on) more than 7h per day.  
We are building our app with cordova for windows and we use Kiosk mode.  
We didn't know if it comes from the PC or something else like ThreeJS.

### Questions 
Do you have any explainations or solutions ?

### Hardware
- Webcam : https://www.dell.com/fr-fr/shop/accessories/apd/a9580031
- PC : https://www.dell.com/fr-fr/shop/cty/pdp/spd/g-series-5090-desktop

**Comment by xavierjs** [comment]
Hi,

Please provide logs from the JS console.
The most likely explanation is that the GPU is overheating, and so the WebGL context is lost.
Refreshing the page won't help unfortunately.
In the nvidia settings you can have the temperature of the GPU.
If the problem is overheating, you can monitor that (the GPU have to stay below 85°C). It will also log something like WARNING: WEBGL_CONTEXT_LOST in the JS console.

The computer case does not seem well ventilated.  If we look at this picture: https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/dell_client_products/desktops/g_series/g5-5090/pdp/desktop_g_series_g5_5090_pdp_mod_1_jp.jpg?fmt=jpg

There is only 1 fan to extract or make air goes into the case. You can add more fans to increase the air flow.
A simpler solution would be to add a liquid cooler to the card.

You can also add a short delay between iterations by running:
```
JEELIZFACEEXPRESSIONS.set_animateDelay(5)
```
(you can increase this value, here 5 ms). Then the GPU will rest a bit.

I would go for another stack: ubuntu/X11/matchbox/electron like in this project: https://github.com/jeeliz/jetsonjs
I run WebGL app on the server side (AWS GPU instances) with this stack, for days, and training of neural networks for weeks. I won't trust windows for this kind of application.

The camera is nice for videoconferencing but the angle is too wide and the face will cover a too small portion of the video if the user is a bit far away. I would opt for an ELP camera, also taking IR (made for security applications first, it will work better on low light conditions), more easily integrable (screwable metal case), cheaper and with a varifocal. Like this one: https://www.amazon.com/dp/B01N8YH5VY

it provides a landscape image but you can unmount it, rotate 90° the PCB and camera and remount it and you get a portrait cam.
