### ISSUE TITLE
init config : isAudio : wrong default value; custom value not applied

### ISSUE THREAD

**Issue by lacastorine** [jeeliz/jeelizWeboji#69]
In `jeelizFaceExpressions.js` `isAudio` is set to `true` by default:
```javascript
...,rotate:0,isAudio:!0,disableRendering:!1...
``` 

Also it is not reassigned to config value in `init(config)` function or anywhere else in lib code.

So lib is asking not only for a camera access, but also for a microphone
<img width="313" alt="image" src="https://github.com/jeeliz/jeelizWeboji/assets/17992666/03ce0101-999d-434a-a6ec-8c5782d2bbdc">

**Comment by xavierjs** [comment]
`isAudio` is set to `true` by default by choice, because JeelizWeboji may be used for karaoke or avatar video conferencing webapps that require audio access.

It can be reassigned, you just need to set `videoSettings: {isAudio: false}` in the init options. In the Three.js helper for example it is set to `false` by default ( https://github.com/jeeliz/jeelizWeboji/blob/74e638d3bca03bae8ea1bf089fc2b3099a0b73b5/helpers/three/JeelizWebojiThreeHelper.js#L32 ). In the raccoon demo the audio access is then not requested.

**Comment by lacastorine** [comment]
My fault, thought `isAudio` should be on the same level as `videoSettings`, not inside it. 
Thanks!
