### ISSUE TITLE
Noise in AU's movement

### ISSUE THREAD

**Issue by MrEveryhand** [jeeliz/jeelizWeboji#9]
Good day!

I succsessefully transfered jeeliz weboji to my project and my 3D models. But movement of morph targets in model goes with strong twitching (for example mouth and eyelids goes wild), which means, that I get signal from AU's with heavy noise. I tried to fix it on my side, by writing some filters. But maybe there is a way or configs on Jeeliz's side to tune AU's noises?

**Comment by xavierjs** [comment]
Hello,

The noise depends a lot on lighting conditions. A strong backlight or a low lighting (the camera with increases its gain so its noise) will increase the noise.

It is very tricky to remove or attenuate the noise in the outputs of the neural network. There are already some internal mechanism to lower the noise. But most noise removal filters lower the responsiveness, which is crucial in this use case (to follow lips movements we need a very high responsiveness...).

If the user is too far there is more noise too. Maybe you can play with the UX and ask him to get closer ( you can get the scale by using `JEETRANSFERTAPI.get_positionScale()[2]` ).

The eyelids are very tricky because the neural network has learned with a bias, he can consider the eye as closed if there are some wrinkles or shadows on the sides of the eyes.

I will improve that, I need to test other neuron network models, but I am currently working on other use-cases.

**Comment by MrEveryhand** [comment]
Thank you very much for replying!
I will try do something with UX and will be waiting for your further development.
